name: Rubocop checks
on: [push, pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read Ruby version from .ruby-version
      run: echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_ENV
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - name: Install gems
      run: gem install rubocop
    - name: Run Rubocop
      run: rubocop
