name: Rubocop checks
on: [push, pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: $(cat .ruby-version)
    - name: Install gems
      run: gem install rubocop
    - name: Run Rubocop
      run: rubocop
