name: Rubocop

on: [push]

permissions:
  actions: maintain
  checks: maintain
  contents: maintain
  deployments: maintain
  id-token: maintain
  issues: maintain
  discussions: maintain
  packages: maintain
  pages: maintain
  pull-requests: maintain
  repository-projects: maintain
  security-events: maintain
  statuses: maintain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.0.0.rc2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
